---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zadara-nas-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-zadara-nas
