---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-from-snapshot
spec:
  storageClassName: csi-zadara-nas
  dataSource:
    name: zadara-snapshot-test
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
