---
apiVersion: v1
kind: Pod
metadata:
  name: zadara-nas-demo-pod-snapshot
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: volume-from-snapshot
        readOnly: false
