---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloned-volume
spec:
  storageClassName: csi-zadara-nas
  dataSource:
    name: zadara-nas-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
