---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloned-volume
spec:
  storageClassName: csi-zadara-block
  dataSource:
    name: zadara-block-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
