---
apiVersion: v1
kind: Pod
metadata:
  name: zadara-block-demo-pod-clone
spec:
  containers:
    - name: web-server
      image: nginx
      volumeDevices:
        - name: mypvc
          devicePath: /dev/sdx
      securityContext:
        # SYS_ADMIN capability to allow 'mount /dev/sdx <path>'
        # Do not use 'privileged: true' - because of a bug in Docker, block device won't appear at devicePath
        capabilities:
          add: ["SYS_ADMIN"]
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: cloned-volume
        readOnly: false
