---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: web-server
          image: nginx
          volumeDevices:
            - name: mypvc
              devicePath: /dev/sdx
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: zadara-block-pvc-multi
            readOnly: false
