---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zadara-block-pvc-multi
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-zadara-block
