---
# Snapshot class
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: zadara-csi-snapclass
snapshotter: csi.zadara.com
---
# Snapshot
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: zadara-snapshot-test
spec:
  snapshotClassName: zadara-csi-snapclass
  source:
    name: zadara-block-pvc
    kind: PersistentVolumeClaim
